import type { Company, Listing } from "./types";

export const SEED_COMPANIES: Company[] = [
  {
    id: "c1",
    name: "AgroFrío Santa Cruz",
    sector: "agro",
    zone: "Warnes",
    contact: "contacto@agrofrio.sc",
    description: "Cadena de frío y almacenamiento agroindustrial.",
  },
  {
    id: "c2",
    name: "Logística Norte SC",
    sector: "logistica",
    zone: "Doble Vía La Guardia",
    contact: "ventas@logisticanorte.bo",
    description: "Transporte de carga y bodegas logísticas.",
  },
  {
    id: "c3",
    name: "MetalMecánica del Este",
    sector: "industria",
    zone: "Plan 3000",
    contact: "info@metalmecanica-este.bo",
    description: "Maquinaria industrial y servicios de mantenimiento.",
  },
  {
    id: "c4",
    name: "TransCargo Bolivia",
    sector: "logistica",
    zone: "El Trompillo",
    contact: "ops@transcargo.bo",
    description: "Flota de camiones y operadores certificados.",
  },
  {
    id: "c5",
    name: "Industrias del Trópico",
    sector: "industria",
    zone: "Centro / Equipetrol",
    contact: "comercial@indtropico.bo",
    description: "Manufactura y espacios de producción compartida.",
  },
  {
    id: "c6",
    name: "EcoRiego SC",
    sector: "agro",
    zone: "Montero",
    contact: "soporte@ecoriego.sc",
    description: "Sistemas de riego y monitoreo agrícola.",
  },
  {
    id: "c7",
    name: "Energía Solar Andina",
    sector: "energia",
    zone: "Urubó",
    contact: "proyectos@solarandina.bo",
    description: "Instalación y mantenimiento de paneles solares.",
  },
  {
    id: "c8",
    name: "AquaTech Santa Cruz",
    sector: "agua",
    zone: "La Guardia",
    contact: "servicio@aquatech.sc",
    description: "Tratamiento de agua y monitoreo de calidad.",
  },
  {
    id: "c9",
    name: "Bodegas del Oriente",
    sector: "logistica",
    zone: "7mo Anillo",
    contact: "alquiler@bodegasoriente.bo",
    description: "Red de bodegas secas y climatizadas.",
  },
  {
    id: "c10",
    name: "TecnoAgro Solutions",
    sector: "agro",
    zone: "Warnes",
    contact: "lab@tecnoagro.bo",
    description: "Laboratorio móvil y personal agronómico.",
  },
  {
    id: "c11",
    name: "Grúas & Montaje SC",
    sector: "industria",
    zone: "Virgen de Cotoca",
    contact: "operaciones@gruas-sc.bo",
    description: "Grúas, montaje industrial y personal certificado.",
  },
  {
    id: "c12",
    name: "Procesadora del Valle",
    sector: "industria",
    zone: "Montero",
    contact: "plantas@procesadoravalle.bo",
    description: "Planta de procesamiento con capacidad ociosa.",
  },
];

export const SEED_LISTINGS: Listing[] = [
  {
    id: "l1",
    kind: "oferta",
    companyId: "c1",
    companyName: "AgroFrío Santa Cruz",
    ownerUserId: "user-oferta-001",
    sector: "agro",
    resourceType: "bodega",
    title: "Bodega refrigerada 500 m²",
    description:
      "Cámara fría certificada para productos agroindustriales. Temperatura 2-8°C. Monitoreo 24/7.",
    zone: "Warnes",
    price: 1200,
    priceUnit: "mes",
    availability: "Disponible inmediato, contrato mínimo 1 mes",
    capacity: "500 m² / 80 toneladas",
    conditions: "Seguro obligatorio. Depósito equivalente a 1 mes.",
    limitations: "No productos químicos peligrosos.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l2",
    kind: "oferta",
    companyId: "c2",
    companyName: "Logística Norte SC",
    sector: "logistica",
    resourceType: "bodega",
    title: "Bodega seca 800 m² con muelle",
    description:
      "Espacio logístico con rampa de carga, seguridad y estacionamiento para 6 camiones.",
    zone: "Doble Vía La Guardia",
    price: 900,
    priceUnit: "mes",
    availability: "Disponible de lunes a sábado",
    capacity: "800 m²",
    conditions: "Contrato mínimo 3 meses. Facturación mensual.",
    limitations: "Sin almacenamiento de inflamables.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l3",
    kind: "oferta",
    companyId: "c3",
    companyName: "MetalMecánica del Este",
    sector: "industria",
    resourceType: "maquinaria",
    title: "Torno CNC + operador especializado",
    description:
      "Torno CNC de precisión con operador certificado. Ideal para piezas industriales y prototipos.",
    zone: "Plan 3000",
    price: 85,
    priceUnit: "hora",
    availability: "Lunes a viernes 14:00-22:00 (turno ocioso)",
    capacity: "Piezas hasta 1.2m diámetro",
    conditions: "Cliente provee planos técnicos. Pago por adelantado 50%.",
    limitations: "No materiales radioactivos ni tóxicos.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l4",
    kind: "oferta",
    companyId: "c4",
    companyName: "TransCargo Bolivia",
    sector: "logistica",
    resourceType: "transporte",
    title: "Camión rígido 8 ton + chofer",
    description:
      "Flota disponible fines de semana para distribución urbana e interdepartamental.",
    zone: "El Trompillo",
    price: 350,
    priceUnit: "dia",
    availability: "Sábados y domingos, reserva con 48h anticipación",
    capacity: "8 toneladas / 40 m³",
    conditions: "Combustible incluido hasta 200 km. Seguro incluido.",
    limitations: "No carga peligrosa clase 1.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l5",
    kind: "oferta",
    companyId: "c5",
    companyName: "Industrias del Trópico",
    sector: "industria",
    resourceType: "infraestructura",
    title: "Línea de empaque ociosa",
    description:
      "Línea automatizada de empaque y etiquetado disponible por turnos. Personal incluido.",
    zone: "Centro / Equipetrol",
    price: 450,
    priceUnit: "dia",
    availability: "Martes y jueves turno noche",
    capacity: "5.000 unidades/día",
    conditions: "Capacitación inicial 4 horas incluida.",
    limitations: "Productos alimenticios requieren certificación BPM.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l6",
    kind: "oferta",
    companyId: "c6",
    companyName: "EcoRiego SC",
    sector: "agro",
    resourceType: "servicio_tecnico",
    title: "Ingeniero agrónomo + equipo de riego",
    description:
      "Consultoría de riego por goteo y instalación temporal de sensores de humedad.",
    zone: "Montero",
    price: 280,
    priceUnit: "dia",
    availability: "Disponible toda la semana",
    capacity: "Hasta 50 hectáreas por visita",
    conditions: "Transporte incluido en radio de 30 km.",
    limitations: "No incluye materiales de riego.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l7",
    kind: "oferta",
    companyId: "c7",
    companyName: "Energía Solar Andina",
    sector: "energia",
    resourceType: "servicio_tecnico",
    title: "Técnico electricista solar certificado",
    description:
      "Mantenimiento preventivo y correctivo de sistemas fotovoltaicos industriales.",
    zone: "Urubó",
    price: 65,
    priceUnit: "hora",
    availability: "Lunes a sábado 8:00-18:00",
    capacity: "Sistemas hasta 500 kW",
    conditions: "Diagnóstico inicial incluido en primera visita.",
    limitations: "No incluye repuestos.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l8",
    kind: "oferta",
    companyId: "c8",
    companyName: "AquaTech Santa Cruz",
    sector: "agua",
    resourceType: "herramientas",
    title: "Kit de monitoreo de calidad de agua",
    description:
      "Sensores portátiles pH, turbidez, cloro. Operador capacitado incluido.",
    zone: "La Guardia",
    price: 180,
    priceUnit: "dia",
    availability: "Disponible inmediato",
    capacity: "Hasta 20 puntos de muestreo/día",
    conditions: "Informe digital incluido en 24h.",
    limitations: "Análisis de laboratorio no incluido.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l9",
    kind: "oferta",
    companyId: "c9",
    companyName: "Bodegas del Oriente",
    sector: "logistica",
    resourceType: "bodega",
    title: "Bodega climatizada 200 m²",
    description:
      "Ideal para productos sensibles a temperatura. Ubicación estratégica 7mo anillo.",
    zone: "7mo Anillo",
    price: 650,
    priceUnit: "mes",
    availability: "Disponible por 6 meses mínimo",
    capacity: "200 m² / 15 toneladas",
    conditions: "Servicio de vigilancia incluido.",
    limitations: "No alimentos sin empaque certificado.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l10",
    kind: "oferta",
    companyId: "c10",
    companyName: "TecnoAgro Solutions",
    sector: "agro",
    resourceType: "personal",
    title: "Equipo agronómico móvil (3 personas)",
    description:
      "Análisis de suelo, detección de plagas y recomendaciones de tratamiento.",
    zone: "Warnes",
    price: 320,
    priceUnit: "dia",
    availability: "Disponible miércoles a sábado",
    capacity: "3 técnicos + vehículo equipado",
    conditions: "Informe técnico en 48h.",
    limitations: "Radio máximo 50 km desde Warnes.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l11",
    kind: "oferta",
    companyId: "c11",
    companyName: "Grúas & Montaje SC",
    sector: "industria",
    resourceType: "maquinaria",
    title: "Grúa telescópica 25 ton + operador",
    description:
      "Montaje industrial, carga pesada y movimiento de maquinaria en planta.",
    zone: "Virgen de Cotoca",
    price: 520,
    priceUnit: "dia",
    availability: "Fines de semana y feriados",
    capacity: "25 toneladas / 30m alcance",
    conditions: "Estudio de suelo previo incluido.",
    limitations: "No operación en zonas de alto tráfico sin permiso.",
    createdAt: "2026-05-29T10:00:00Z",
  },
  {
    id: "l12",
    kind: "oferta",
    companyId: "c12",
    companyName: "Procesadora del Valle",
    sector: "industria",
    resourceType: "capacidad_operativa",
    title: "Turno de procesamiento en planta",
    description:
      "Capacidad ociosa en planta de procesamiento de granos. Personal calificado incluido.",
    zone: "Montero",
    price: 800,
    priceUnit: "dia",
    availability: "Lunes, miércoles y viernes turno tarde",
    capacity: "20 toneladas/día",
    conditions: "Certificación de producto requerida.",
    limitations: "Solo productos agrícolas secos.",
    createdAt: "2026-05-29T10:00:00Z",
  },
];
